executable:
  source-dirs: src
  main: Prompt
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base
- split
- aeson
- bytestring
- stm
- text
- time
- thyme
- directory
- pretty-simple
- string-conversions
- optparse-applicative
- directory
- filepath
- time
- MissingH
- safe
name: sodiumSierraStrawberry
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
